/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{svelte,js,ts,jsx,tsx}'],
  theme: {"name": "Seti",
    "black": "#323232",
    "red": "#c22832",
    "green": "#8ec43d",
    "yellow": "#e0c64f",
    "blue": "#43a5d5",
    "purple": "#8b57b5",
    "cyan": "#8ec43d",
    "white": "#eeeeee",
    "brightBlack": "#323232",
    "brightRed": "#c22832",
    "brightGreen": "#8ec43d",
    "brightYellow": "#e0c64f",
    "brightBlue": "#43a5d5",
    "brightPurple": "#8b57b5",
    "brightCyan": "#8ec43d",
    "brightWhite": "#ffffff",
    "foreground": "#cacecd",
    "background": "#111213",
    "cursorColor": "#cacecd"},
  plugins: [],
};
